// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYuE7stADYyB-NmRmALL7T_klMU-J1yg',
    appId: '1:1026165866514:web:1b342b1f9d182f1f7498cb',
    messagingSenderId: '1026165866514',
    projectId: 'chatapp-74319',
    authDomain: 'chatapp-74319.firebaseapp.com',
    storageBucket: 'chatapp-74319.appspot.com',
    measurementId: 'G-XCGG1JVRT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTvn9i49SHuUaOtDm0C5C9GZc2p8AKNw',
    appId: '1:1026165866514:android:1649b8f1f3c40a437498cb',
    messagingSenderId: '1026165866514',
    projectId: 'chatapp-74319',
    storageBucket: 'chatapp-74319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKkhZ9XWEYj0meEtiHnJ2Nzo67veihSsk',
    appId: '1:1026165866514:ios:4de86da4d544f9717498cb',
    messagingSenderId: '1026165866514',
    projectId: 'chatapp-74319',
    storageBucket: 'chatapp-74319.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKkhZ9XWEYj0meEtiHnJ2Nzo67veihSsk',
    appId: '1:1026165866514:ios:94564a4500e3dab67498cb',
    messagingSenderId: '1026165866514',
    projectId: 'chatapp-74319',
    storageBucket: 'chatapp-74319.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
